### ISSUE TITLE
ToBaCCo creates MOFs with all organic nodes

### ISSUE THREAD

**Issue by tdpham2** [tobacco-mofs/tobacco_3.0#11]
**Description**

ToBaCCo occasionally creates MOFs with all organic nodes.

**To Reproduce**
For example, I used the following template, nodes and edges provided in templates_database, nodes_database and edges_database:

Template: kkm.cif
Nodes: 3c_triazine_Ch.cif and 6c_bicyclooctane_Ch.cif
Edges: 1B_1TrU.cif and 2B_4F_Ch.cif

With ToBaCCo default settings (no change to tobacco.py and configuration.py), this generates 4 MOFs with all organic nodes.

**Comment by rytheranderson** [comment]
If the SINGLE_METAL_MOFS_ONLY =False in configuration.py no cifs are written using the above building blocks and template. If SINGLE_METAL_MOFS_ONLY=True there is no check for all-organic structures (this allows users to build COFs and POCs, etc.). Please raise another issue if you find an instance were SINGLE_METAL_MOFS_ONLY=True and all-organic structures are written.
