### ISSUE TITLE
COMBINATORIAL_EDGE_ASSIGNMENT issue

### ISSUE THREAD

**Issue by tdpham2** [tobacco-mofs/tobacco_3.0#12]
**Description**

I am trying to create the same MOF using tobacco by setting COMBINATORIAL_EDGE_ASSIGNMENT = False (along with USER_SPECIFIED_NODE_ASSIGNMENT tag appropriately) in configuration.py. However, tobacco seems to create different MOFs at random.

**Reproduce**
 
To reproduce, below are the settings and files that I used. All CIF files are from tobacco 3.0 database.
CIF files:
template: stc.cif
node: 6c_Cu_1_Ch.cif
edges: 1B_1TrU.cif, 1B_2NH2_Ch.cif and 1B_2SH_Ch.cif

Settings:
COMBINATORIAL_EDGE_ASSIGNMENT = False. Since there was only 1 given node, USER_SPECIFIED_NODE_ASSIGNMENT was not used. 

I ran tobacco with the above setting 10-20 times, and because of the setting, only 1 MOF was created for every tobacco iteration. I expected every MOF created to be the same (because there is only one node, and from tobacco manual, edges are assigned in in canonical alphanumeric order). However, I found at least 3 different structures created from this setting (1 of the structures had different number of " S " atoms in the CIF file from the other two)

The same issue also happened with USER_SPECIFIED_NODE_ASSIGNMENT =  True (not shown in details here).

**Comment by KunhuanLiu** [comment]
After some investigation I believe the order of assigning EA to edge type is not consistent, due to the use of set() in this line:
ciftemplate2graph.py line 215: 
`yield (SG, start, unit_cell, set(cns), set(e_types), cifname, aL, bL, cL, alpha, beta, gamma, max_le, catenation)`

**Comment by rytheranderson** [comment]
Thanks for pointing this out, what was happening it the actual edge order changed with different iterations, i.e.

iteration 1:
{(V,V),(Er,V)(Er,Er)}
iteration 2:
{(Er,V),(V,V)(Er,Er)}

meaning that even though the edge building blocks were assigned consistently to edge 1, 2, and 3, these edge types were not consistent. I have added the line:

TET = sorted(TET, reverse=True)

(now line 92 in tobacco.py)

which should fix this issue, I confirmed that the output MOF composition was the same for 10 iterations:
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
[('C', 282), ('Cu', 24), ('H', 180), ('N', 36), ('O', 96), ('S', 18)]
