### ISSUE TITLE
contains no metals or multiple metal elements, no cif will be written

### ISSUE THREAD

**Issue by longzhanyuye5** [tobacco-mofs/tobacco_3.0#15]
I'd like to ask why do we still need metal atoms to build cifs after X atoms added.

**Comment by rytheranderson** [comment]
Hello,

Please see the documentation section 7.23:

7.23 SINGLE_METAL_MOFS_ONLY [True | False]
If True, ToBaCCo will only output MOFs that have nodes with no more than one metal. This is useful for building large databases where multi-metal MOFs are not wanted.

ToBaCCo does not distinguish between nodular building blocks, any "node" added to the nodes directory is used as a node whether or not it has metals in it. However, it is often the case that we don't want to build any covalent organic frameworks or multi-metal MOFs. If you want to build structures without metals, just use SINGLE_METAL_MOFS_ONLY = False.

**Comment by rytheranderson** [comment]
I updated the documentation to make the SINGLE_METAL_MOFS only flag more clear.
