### ISSUE TITLE
Is it possible to work with nodes that periodically go across unit cells?

### ISSUE THREAD

**Issue by fbjfbj** [tobacco-mofs/tobacco_3.0#17]
I'm wondering if it is possible to work with the nodes that periodically go across unit cells and connect together without any edge in between them, as I noticed in the manual that you need to place the node in a much larger box in order to make the tobacco code work. 

I attach at example of node 
[123_node.cif.txt](https://github.com/tobacco-mofs/tobacco_3.0/files/6077123/123_node.cif.txt)
. 

I get this node from a MOF like this
[orig_mol.cif.txt](https://github.com/tobacco-mofs/tobacco_3.0/files/6077148/orig_mol.cif.txt), and I'm wondering if you can reconstruct a MOF like this?

**Comment by rytheranderson** [comment]
It is possible, but you will need to decompose the node into a set of non-periodic nodes/edges, this may require a custom topological template depending on how you go about it. I have reconstructed MIL-47/53 analogs in this way.

**Comment by fbjfbj** [comment]
Thank you very much for your quick reply. I'm wondering if it is possible to have a set of example on MIL-47/53, for example, in the databases on GIt showing how this kind of MOF reconstruction is achieved? Thanks again.

**Comment by rytheranderson** [comment]
Yes that is a good idea, I can make an example for the MIL-type MOFs. I am preparing my thesis currently, so I will not get to it until ~1 month from now. However, if you want to make an attempt and it works well I can include it in the git repo.

**Comment by fbjfbj** [comment]
Thank you. I'll give it a try, but I'm not sure whether I'll succeed since I'm not a chemist and I'm not very familiar with the cif file format. I'll let you know if I make a successful attempt. Otherwise, I'll wait when you get the chance to look at it. Thanks again.
