### ISSUE TITLE
fractional coords outside [0, 1]

### ISSUE THREAD

**Issue by SimonEnsemble** [tobacco-mofs/tobacco_3.0#18]
when tobacco generates `.cif` files, we are seeing it put fractional coordinates outside of the interval [0, 1]. this might affect downstream processing (not sure if most molecular simulation codes internally wrap to [0, 1] or what).
just suggesting it might be worth to put a `mod(xf, 1.0)` around the fractional coordinates before tobacco writes to `.cif`.

```
Zn4       Zn   -0.0424003287    0.0424003287   -0.0424003287          1.4948
O5         O    0.0000000000    0.0000000000    0.0000000000          -2.30
```

**Comment by rytheranderson** [comment]
Hello SimonEnsemble,

Thanks for raising this issue, for LAMMPS, RASPA, and zeo++ I am reasonably sure that there are no problems with having fractional coordinates outside the range [0,1] (I have tested in the past for a variety of CIF formats). For other codes I am not sure, I doubt it would be an issue but I suppose you never know, so I added an np.mod command to the fractional coordinates before the CIF is written.
