### ISSUE TITLE
Some topology files are supercells

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tobacco-mofs/tobacco_3.0#5]
Because of how I was originally setting up the bond detection, some of the topology files are supercells and could be made smaller (e.g. see `fcu.cif`). This will be fixed shortly (next few days) in a PR. I decided to largely rewrite my [`make_topologies.py`](https://github.com/arosen93/tobacco_3.0/blob/master/make_topologies.py) script in a much better way, which resolves this problem. Progress can be tracked at https://github.com/arosen93/tobacco_3.0. I am just running some checks.

**Comment by rytheranderson** [comment]
Thanks Andrew, in principle the large supercells are fine (especially for use in MD simulations), but I think for use in RASPA the cells should start as small as possible, which is especially important for cells that are already over 25 Å in each dimension.

**Comment by Andrew-S-Rosen** [comment]
We are actively working on the problem over here. We have a few small kinks to work out but should hopefully be done soon.

**Comment by Andrew-S-Rosen** [comment]
I believe this has now been resolved. Before I open the PR: @aromaticSesame, can you please first take a look at my fork and do some quick tests to sanity check me here? Thanks.

**Comment by rytheranderson** [comment]
Thanks, I checked the cif embeddings of the ~50 topologies I am most familiar with, they all seem to be a minimal unit. I also ran a "random" selection of 20 nets, everything looks good to me.

**Comment by Andrew-S-Rosen** [comment]
Great, thanks. I will do some remaining checks tonight and submit the PR tomorrow, unless @aromaticSesame finds anything alarming.

Just for clarity: the only time it will scale up a topology now is if a lattice constant is < the vertex-vertex "bond" distance (to prevent something like "V1 V1 10.0 1_554" in the symmetry information). This is rare though and I imagine a necessary condition nonetheless (and would only happen for small unit cells anyway). Let me know if ToBaCCo can handle something like "V1 V1 10.0 1_554", in which case I can just disable that by commenting out lines 198-199 in make_topologies.py. My guess was that this is not possible.

**Comment by Andrew-S-Rosen** [comment]
Hi @rytheranderson. We are almost there. For the bcg template, 8c_Zr_1_Ch.cif node, and 1B_4H_Ch.cif edge, I get the following error. The indices all seem to be appropriately labeled, the coordination numbers look okay, and a somewhat quick glance suggests the bonding directions are okay. Any suggestions?

```
=========================================================================================================
template : bcg.cif
=========================================================================================================

Number of vertices =  8
Number of edges =  32

*****************************************************************
RMSD of the compatible node BBs with assigned vertices:
*****************************************************************

vertex V (8 connected)
     8c_Zr_1_Ch.cif deviation = 0.34275 (within tolerance)
* 1 compatible building blocks out of 1 available for node V *

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
vertex assignment :  ['v1-8c_Zr_1_Ch.cif']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
edge assignment :  ('1B_4H_Ch.cif',)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "tobacco.py", line 213, in <module>
    all_SBU_coords = SBU_coords(TG, ea_dict, CONNECTION_SITE_BOND_LENGTH)
  File "/home/asr731/software/tobacco_3.0/SBU_geometry.py", line 31, in SBU_coords
    xvecname,dx_v,xvec = ea_dict[vertex][ind]
KeyError: 16
```

**Comment by rytheranderson** [comment]
@arosen93 this is an error that happens when the shape of the node matches the shape of the net vertex very poorly (probably no MOF would exist from this combination of net and node). I looked at the bcg template, it looks OK.

Anyway, I think the templates good to go, thanks for all your contributions.

**Comment by Andrew-S-Rosen** [comment]
Thanks for checking and for your patience with these updates. Happy MOF making!
